// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDPsNnz09ZHhFWUdbBj8H--mmokdo2XBs',
    appId: '1:880365390169:web:fca2cbc24498772ddca448',
    messagingSenderId: '880365390169',
    projectId: 'flutterppb-59708',
    authDomain: 'flutterppb-59708.firebaseapp.com',
    storageBucket: 'flutterppb-59708.firebasestorage.app',
    measurementId: 'G-SSJ3ZYQE7H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzms9j3WL3rmWgmaM2CZZcGWnFDmfg2OM',
    appId: '1:880365390169:android:1c8e63842a9a8181dca448',
    messagingSenderId: '880365390169',
    projectId: 'flutterppb-59708',
    storageBucket: 'flutterppb-59708.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQ9IFURPTWXNxtkJz-i2K2CxFniMLH31k',
    appId: '1:880365390169:ios:b15e2c1967b81e1fdca448',
    messagingSenderId: '880365390169',
    projectId: 'flutterppb-59708',
    storageBucket: 'flutterppb-59708.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplicationFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQ9IFURPTWXNxtkJz-i2K2CxFniMLH31k',
    appId: '1:880365390169:ios:b15e2c1967b81e1fdca448',
    messagingSenderId: '880365390169',
    projectId: 'flutterppb-59708',
    storageBucket: 'flutterppb-59708.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplicationFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCDPsNnz09ZHhFWUdbBj8H--mmokdo2XBs',
    appId: '1:880365390169:web:8612bd8ae59a2affdca448',
    messagingSenderId: '880365390169',
    projectId: 'flutterppb-59708',
    authDomain: 'flutterppb-59708.firebaseapp.com',
    storageBucket: 'flutterppb-59708.firebasestorage.app',
    measurementId: 'G-BEQT2XG94G',
  );
}
